package sspq;


import sspq.util.Refercence;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class CraftingRecipeForRider {
	public static void Crafrting(){
		
	//	GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":masked_rider_head"), new ResourceLocation(Refercence.MODID+":masked_rider"),new ItemStack(RiderItems.masked_rider_head,1), "aaa","a a", 'a', RiderItems.ecto_gem);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorengerhead"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorengerhead,1), "aaa","a a", 'a', RiderItems.gorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorengertroso"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorengertroso,1), "a a","aaa","aaa", 'a', RiderItems.gorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorengerlegs"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorengerlegs,1), "aaa","a a","a a", 'a', RiderItems.gorenger_star);

			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_akarenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_akarenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.akarenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_aorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_aorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.aorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_kirenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_kirenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.kirenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_momorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_momorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.momorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_midorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_midorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.midorenger_star);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_orenjirenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_orenjirenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.orenjirenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_kurorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_kurorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.kurorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_shirorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_shirorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.shirorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_gurerenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_gurerenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.gurerenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_murasakinorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_murasakinorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.murasakinorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_baiorettorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_baiorettorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.baiorettorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_kasshokurenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_kasshokurenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.kasshokurenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_ginrenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_ginrenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.ginrenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_gorudorenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_gorudorenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.gorudorenger_star);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gorenger_belt_shianrenger"), new ResourceLocation(Refercence.MODID+":gorenger"),new ItemStack(RiderItems.gorenger_belt_shianrenger,1), "aaa","aba","aaa", 'a', RiderItems.gorenger_star, 'b', RiderItems.shianrenger_star);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaigerhead"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaigerhead,1), "aaa","a a", 'a', RiderItems.blank_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaigertroso"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaigertroso,1), "a a","aaa","aaa", 'a', RiderItems.blank_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaigerlegs"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaigerlegs,1), "aaa","a a","a a", 'a', RiderItems.blank_ranger_key);

			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_red"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_red,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_red_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_blue"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_blue,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_blue_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_yellow"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_yellow,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_yellow_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_green"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_green,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_green_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_pink"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_pink,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_pink_ranger_key);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_orange"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_orange,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_orange_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_black"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_black,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_black_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_white"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_white,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_white_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_purple"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_purple,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_purple_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_violet"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_violet,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_violet_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_gray"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_gray,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_gray_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_brown"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_brown,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_brown_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":mobirate_gokai_cyan"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.mobirate_gokai_cyan,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_cyan_ranger_key);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaicellular_gokai_silver"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaicellular_gokai_silver,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_silver_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaicellular_gokai_gold"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaicellular_gokai_gold,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_gold_ranger_key);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gokaicellular_gokai_dark"), new ResourceLocation(Refercence.MODID+":gokaiger"),new ItemStack(RiderItems.gokaicellular_gokai_dark,1), "aaa","aba","aaa", 'a', RiderItems.blank_ranger_key, 'b', RiderItems.gokai_dark_ranger_key);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kyoryugerhead"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryugerhead,1), "aaa","a a", 'a', RiderItems.empty_zyudenchi);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kyoryugertroso"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryugertroso,1), "a a","aaa","aaa", 'a', RiderItems.empty_zyudenchi);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":kyoryugerlegs"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryugerlegs,1), "aaa","a a","a a", 'a', RiderItems.empty_zyudenchi);

			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_red"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_red,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_black"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_black,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.parasagun_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_blue"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_blue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.stegotchi_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_green"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_green,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.zakutor_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_pink"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_pink,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.dricera_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburichanger_kyoryu_gold"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburichanger_kyoryu_gold,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburichanger),Ingredient.fromItem(RiderItems.pteragordon_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":spirit_zyudenchi_kyoryu_cyan"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.spirit_zyudenchi_kyoryu_cyan,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_zyudenchi),Ingredient.fromItem(RiderItems.ankydon_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_cyan"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_cyan,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.ankydon_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":spirit_zyudenchi_kyoryu_gray"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.spirit_zyudenchi_kyoryu_gray,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_zyudenchi),Ingredient.fromItem(RiderItems.bunpachy_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_gray"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_gray,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.bunpachy_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_violet"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_violet,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.plezuon_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gigagaburevolver_kyoryu_silver"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gigagaburevolver_kyoryu_silver,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gigagaburevolver),Ingredient.fromItem(RiderItems.bragigas_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_yellow"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_yellow,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.deinochaser_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_orange"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_orange,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.deinosgrander_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_aqua"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_aqua,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.kentorospiker_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_magenta"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_magenta,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.stymero_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_crimson"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_crimson,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.allomerus_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gigagaburevolver_kyoryu_indigo"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gigagaburevolver_kyoryu_indigo,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gigagaburevolver),Ingredient.fromItem(RiderItems.beyonsmo_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_vermilion"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_vermilion,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.ovirappoo_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_lavender"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_lavender,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.igeranodon_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburichanger_kyoryu_white"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburichanger_kyoryu_white,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburichanger),Ingredient.fromItem(RiderItems.tuperanda_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_limegreen"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_limegreen,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.gurumonite_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_cobalt"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_cobalt,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.archenolon_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_scarlet"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_scarlet,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.pukuptor_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_lightgray"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_lightgray,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.futabain_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gigagaburevolver_kyoryu_neongreen"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gigagaburevolver_kyoryu_neongreen,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gigagaburevolver),Ingredient.fromItem(RiderItems.speedrus_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_royalblue"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_royalblue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.prisukeos_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburichanger_kyoryu_lightblue"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburichanger_kyoryu_lightblue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburichanger),Ingredient.fromItem(RiderItems.fuwanycto_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_darkgray"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_darkgray,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.kachicox_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_firered"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_firered,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.karateta_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_neonyellow"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_neonyellow,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.taekwondonto_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_brown"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_brown,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.manoki_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_purple"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_purple,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.ichthyogu_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_kyoryu_navy"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_kyoryu_navy,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.tobaspino_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver_deathryuger"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver_deathryuger,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.deathryuger_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabutyra_de_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gabutyra_de_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.minityra),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_red_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_red_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_black_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_black_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.parasagun_zyudenchi),Ingredient.fromItem(RiderItems.parasagun_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_blue_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_blue_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.stegotchi_zyudenchi),Ingredient.fromItem(RiderItems.stegotchi_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_green_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_green_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.zakutor_zyudenchi),Ingredient.fromItem(RiderItems.zakutor_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_pink_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_pink_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.dricera_zyudenchi),Ingredient.fromItem(RiderItems.dricera_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kyoryu_gold_armed_on"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kyoryu_gold_armed_on,1), new Ingredient[]{Ingredient.fromItem(RiderItems.pteragordon_zyudenchi),Ingredient.fromItem(RiderItems.pteragordon_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":samba_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.samba_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.stegotchi_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.dricera_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":western_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.western_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.parasagun_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.zakutor_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":macho_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.macho_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.ankydon_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.dricera_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":kung_fu_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.kung_fu_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.ankydon_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.bunpachy_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":special_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.special_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.stegotchi_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.tobaspino_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":tv_maga_carnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.tv_maga_carnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.plezuon_zyudenchi),Ingredient.fromItem(RiderItems.gabutyra_zyudenchi),Ingredient.fromItem(RiderItems.ankydon_zyudenchi),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gaburevolver"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburevolver,1), "aaa","aba","aaa", 'a', RiderItems.empty_zyudenchi, 'b', Items.DIAMOND_SWORD);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gaburichanger"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburichanger,1), "aba","aaa","aaa", 'a', RiderItems.empty_zyudenchi, 'b', Items.DIAMOND_SWORD);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gigagaburevolver"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gigagaburevolver,1), "aba","aba","aba", 'a', RiderItems.empty_zyudenchi, 'b', Items.DIAMOND_SWORD);
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":minityra"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.minityra,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.carnival_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gaburicarnival"), new ResourceLocation(Refercence.MODID+":kyoryuger"),new ItemStack(RiderItems.gaburicarnival,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gaburevolver),Ingredient.fromItem(RiderItems.minityra)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":brave_kyoryugerhead"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.brave_kyoryugerhead,1), "aaa","a a", 'a', RiderItems.empty_zyudenchi);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":brave_kyoryugertroso"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.brave_kyoryugertroso,1), "a a","aaa","aaa", 'a', RiderItems.empty_zyudenchi);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":brave_kyoryugerlegs"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.brave_kyoryugerlegs,1), "aaa","a a","a a", 'a', RiderItems.empty_zyudenchi);

			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver_brave_kyoryu_red"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver_brave_kyoryu_red,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburevolver),Ingredient.fromItem(RiderItems.guntyra_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver_brave_kyoryu_black"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver_brave_kyoryu_black,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburevolver),Ingredient.fromItem(RiderItems.stegonsaw_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver_brave_kyoryu_blue"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver_brave_kyoryu_blue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburevolver),Ingredient.fromItem(RiderItems.shovecera_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver_brave_kyoryu_green"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver_brave_kyoryu_green,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburevolver),Ingredient.fromItem(RiderItems.parasaber_zyudenchi)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver_brave_kyoryu_pink"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver_brave_kyoryu_pink,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburevolver),Ingredient.fromItem(RiderItems.rapx_zyudenchi)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":gabugaburichanger_brave_kyoryu_gold"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburichanger_brave_kyoryu_gold,1), new Ingredient[]{Ingredient.fromItem(RiderItems.gabugaburichanger),Ingredient.fromItem(RiderItems.pteravolt_zyudenchi)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gabugaburevolver"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburevolver,1), "aaa","aba","aaa", 'a', RiderItems.empty_brave_zyudenchi, 'b', Items.DIAMOND_SWORD);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gabugaburichanger"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gabugaburichanger,1), "aba","aaa","aaa", 'a', RiderItems.empty_brave_zyudenchi, 'b', Items.DIAMOND_SWORD);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":gigagabugaburevolver"), new ResourceLocation(Refercence.MODID+":brave_kyoryuger"),new ItemStack(RiderItems.gigagabugaburevolver,1), "aba","aba","aba", 'a', RiderItems.empty_brave_zyudenchi, 'b', Items.DIAMOND_SWORD);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupinhead"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupinhead,1), "aaa","a a", 'a', RiderItems.lupinranger_badge);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupintroso"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupintroso,1), "a a","aaa","aaa", 'a', RiderItems.lupinranger_badge);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupinlegs"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupinlegs,1), "aaa","a a","a a", 'a', RiderItems.lupinranger_badge);

			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_red"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_red,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_lupin),Ingredient.fromItem(RiderItems.red_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_blue"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_blue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_lupin),Ingredient.fromItem(RiderItems.blue_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_yellow"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_yellow,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_lupin),Ingredient.fromItem(RiderItems.yellow_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_black"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_black,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.scissors_dial_fighter),Ingredient.fromItem(RiderItems.blade_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_green"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_green,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.cyclone_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_white"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_white,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.magic_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_gray"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_gray,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_silver),Ingredient.fromItem(RiderItems.victory_striker)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_prism"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_prism,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.prism_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_paint"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_paint,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.paint_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_music"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_music,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.music_dial_fighter)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_jackpot"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_jackpot,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_red_lupin),Ingredient.fromItem(RiderItems.jackpot_striker)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":jackpot_striker_lupin_tricolor"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.jackpot_striker_lupin_tricolor,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_lupin),Ingredient.fromItem(RiderItems.jackpot_striker)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":x_changer_lupin_x"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.x_changer_lupin_x,1), new Ingredient[]{Ingredient.fromItem(RiderItems.lupin_x_changer),Ingredient.fromItem(RiderItems.x_train_silver)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":storm_changer_lupin_fire_storm"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.storm_changer_lupin_fire_storm,1), new Ingredient[]{Ingredient.fromItem(RiderItems.lupin_storm_changer),Ingredient.fromItem(RiderItems.x_train_fire)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":prision_changer_lupin_prision_chain"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.prision_changer_lupin_prision_chain,1), new Ingredient[]{Ingredient.fromItem(RiderItems.lupin_prision_changer),Ingredient.fromItem(RiderItems.x_train_chain)});
		
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin_striker"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin_striker,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_lupin),Ingredient.fromItem(RiderItems.goodstriker_lupin_mode)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.red_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin1"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.blue_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_lupin2"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.yellow_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.scissors_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin1"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.blade_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin2"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.cyclone_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin3"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.magic_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin4"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.prism_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin5"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.paint_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin6"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.goodstriker_lupin_mode);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_lupin7"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_black_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.music_dial_fighter);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_red_lupin"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_red_lupin,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.jackpot_striker);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_gold"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.vs_changer_gold,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.victory_striker);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupin_magnum"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupin_magnum,1), "aaa","aba","aaa", 'a', RiderItems.red_dial_fighter, 'b', RiderItems.vs_changer_lupin);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupin_x_changer"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupin_x_changer,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_silver);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupin_storm_changer"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupin_storm_changer,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_fire);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":lupin_prision_changer"), new ResourceLocation(Refercence.MODID+":lupinranger"),new ItemStack(RiderItems.lupin_prision_changer,1), "aaa","aba","ama", 'a', RiderItems.lupinranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_chain);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patrenhead"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patrenhead,1), "aaa","a a", 'a', RiderItems.patranger_badge);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patrentroso"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patrentroso,1), "a a","aaa","aaa", 'a', RiderItems.patranger_badge);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patrenlegs"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patrenlegs,1), "aaa","a a","a a", 'a', RiderItems.patranger_badge);

			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_1go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_1go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_patren),Ingredient.fromItem(RiderItems.trigger_machine_1go)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_2go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_2go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_patren),Ingredient.fromItem(RiderItems.trigger_machine_2go)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_3go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_3go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_patren),Ingredient.fromItem(RiderItems.trigger_machine_3go)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_4go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_4go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_biker)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_5go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_5go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_crane),Ingredient.fromItem(RiderItems.trigger_machine_drill)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_6go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_6go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_splash)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_7go"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_7go,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_gold),Ingredient.fromItem(RiderItems.siren_striker)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_flash"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_flash,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_flash)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_dog"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_dog,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_dog)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_music"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_music,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_music)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_cement"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_cement,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_cement)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_christmas"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_christmas,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.trigger_machine_christmas)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_justice"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_justice,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_red_patren),Ingredient.fromItem(RiderItems.justice_striker)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":goodstriker_patren_ugo"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.goodstriker_patren_ugo,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_patren),Ingredient.fromItem(RiderItems.goodstriker_patren_mode)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":x_changer_patren_x"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.x_changer_patren_x,1), new Ingredient[]{Ingredient.fromItem(RiderItems.patren_x_changer),Ingredient.fromItem(RiderItems.x_train_gold)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":storm_changer_patren_thunder_storm"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.storm_changer_patren_thunder_storm,1), new Ingredient[]{Ingredient.fromItem(RiderItems.patren_storm_changer),Ingredient.fromItem(RiderItems.x_train_thunder)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":prision_changer_patren_prision_jail"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.prision_changer_patren_prision_jail,1), new Ingredient[]{Ingredient.fromItem(RiderItems.patren_prision_changer),Ingredient.fromItem(RiderItems.x_train_jail)});
			
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren_striker"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren_striker,1), new Ingredient[]{Ingredient.fromItem(RiderItems.vs_changer_black_patren),Ingredient.fromItem(RiderItems.goodstriker_patren_mode)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_1go);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren1"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_2go);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_patren2"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_3go);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_biker);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren1"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_crane);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren2"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_drill);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren3"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_splash);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren4"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_flash);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren5"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.trigger_machine_dog);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_black_patren6"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_black_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.goodstriker_patren_mode);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":vs_changer_red_patren"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.vs_changer_red_patren,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.justice_striker);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patren_x_changer"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patren_x_changer,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_gold);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patren_storm_changer"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patren_storm_changer,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_thunder);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":patren_prision_changer"), new ResourceLocation(Refercence.MODID+":patranger"),new ItemStack(RiderItems.patren_prision_changer,1), "aaa","aba","ama", 'a', RiderItems.patranger_badge, 'b', Items.DIAMOND_SWORD, 'm', RiderItems.x_train_jail);
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryusoulhead"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoulhead,1), "aaa","a a", 'a', RiderItems.blank_ryusoul);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryusoultroso"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoultroso,1), "a a","aaa","aaa", 'a', RiderItems.blank_ryusoul);
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryusoullegs"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoullegs,1), "aaa","a a","a a", 'a', RiderItems.blank_ryusoul);

			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_changer_ryusoul_red"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_changer_ryusoul_red,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_ryusoul_changer),Ingredient.fromItem(RiderItems.ryusoul_red)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_changer_ryusoul_black"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_changer_ryusoul_black,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_ryusoul_changer),Ingredient.fromItem(RiderItems.ryusoul_black)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_changer_ryusoul_blue"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_changer_ryusoul_blue,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_ryusoul_changer),Ingredient.fromItem(RiderItems.ryusoul_blue)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_changer_ryusoul_green"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_changer_ryusoul_green,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_ryusoul_changer),Ingredient.fromItem(RiderItems.ryusoul_green)});
			GameRegistry.addShapelessRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_changer_ryusoul_pink"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_changer_ryusoul_pink,1), new Ingredient[]{Ingredient.fromItem(RiderItems.empty_ryusoul_changer),Ingredient.fromItem(RiderItems.ryusoul_pink)});
			
			GameRegistry.addShapedRecipe(new ResourceLocation(Refercence.MODID+":ryusoul_ken"), new ResourceLocation(Refercence.MODID+":ryusoulger"),new ItemStack(RiderItems.ryusoul_ken,1), "aaa","aba","aaa", 'a', RiderItems.blank_ryusoul, 'b', Items.DIAMOND_SWORD);			
			
	}
}
